---
- hosts: all
  sudo_user: "{{ ansible_ssh_user }}"
  tasks:
  - include: tasks/apt.yml
  - include: tasks/ufw.yml
  - include: tasks/nodejs.yml
  - include: tasks/misc.yml
  - include: tasks/docker.yml
