---
# Install Docker
# https://docs.docker.com/installation/ubuntulinux/
- name: Check if docker is installed
  command: docker -v
  register: docker
  ignore_errors: True
  changed_when: False

- name: Install Docker
  sudo: yes
  shell: curl -sL https://get.docker.com/ | sudo bash -
  when: docker.rc != 0

# We need docker-py to use the docker ansible module
- name: Install pip (python)
  sudo: yes
  apt:
    name: python-pip
    state: present

- name: Install docker-py (for ansible compatibility.)
  sudo: yes
  pip:
    name: docker-py
    state: present

